name: Tool request
description: File a tool request
title: "[add]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ### Instructions
        Thanks for taking the time to fill out this tool request! You can get badges from https://shields.io. You'll need:

        - Stars: eg. `https://img.shields.io/github/stars/USER_NAME/REPO_NAME`
        - Last Commit: eg. `https://img.shields.io/github/last-commit/USER_NAME/REPO_NAME?label=`
        - Top Language: eg. `https://img.shields.io/github/languages/top/USER_NAME/REPO_NAME`

        Replace `USER_NAME` & `REPO_NAME` with appropriate values in the following from. Then you may comment out this section.
  - type: input
    id: name
    attributes:
      label: Name
      description: Please name the tool
      placeholder: eg. trashy
    validations:
      required: true
  - type: input
    id: source
    attributes:
      label: Source
      description: Provide url to the source code
      placeholder: eg. https://github.com/oberblastmeister/trashy
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a description for the tool
      placeholder: eg. a cli system trash manager, alternative to rm and trash-cli
    validations:
      required: true
  - type: textarea
    id: stars
    attributes:
      label: Stars
      description: Provide a link to stars badge
      placeholder: eg. https://img.shields.io/github/stars/oberblastmeister/trashy
    validations:
      required: true
  - type: textarea
    id: status
    attributes:
      label: Status
      description: Provide a link to status badge
      placeholder: eg. https://img.shields.io/github/last-commit/oberblastmeister/trashy?label=
    validations:
      required: true
  - type: textarea
    id: language
    attributes:
      label: Language
      description: Provide a link to language badge
      placeholder: eg. https://img.shields.io/github/languages/top/oberblastmeister/trashy
    validations:
      required: true
  - type: textarea
    id: preview
    attributes:
      label: Preview
      description: Provide a link to tool's image/gif preview
      placeholder: eg. ![preview](https://raw.githubusercontent.com/oberblastmeister/trashy/master/doc/trashy_demo_1.gif)
    validations:
      required: true
